### Autosuggest place name
GET http://localhost:8080/v1/place-names/prefix/york?max_results=10
Accept: application/json

### Healthcheck
GET http://localhost:8080/healthz
Accept: application/json

### Prometheus
GET http://localhost:8080/metrics
Accept: application/json

### CORS Preflight
OPTIONS http://localhost:8080/v1/place-names/prefix/york
Access-Control-Request-Method: GET
Origin: http://example.com